name: DB_MIGRATION_CD

on:
  workflow_call:
    inputs:
      userdb:
        type: string
        required: true
      reportdb:
        type: string
        required: true
      scope3db:
        type: string
        required: true
    secrets:
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  user-db-migration:
    needs: changes
    if: ${{ github.event.inputs.user_db == 'true' }}
    uses: ./.github/workflows/user-db-cd.yml
    secrets: inherit
