name: App workflow

on:
  workflow_call:
    inputs:
      app1:
        type: string
        required: true
    secrets:
      SECRET_1:
        required: true

jobs:
  call-app1:
    if: ${{ github.event.inputs.app1 == 'true' }}
    uses: ./.github/workflows/workflow-app1.yml
    secrets: inherit

  # call-app1:
  #   uses: ./.github/workflows/workflow-app1.yml
  #   secrets: inherit
