name: Main workflow

on:
  push:
    paths:
      - 'infrastructure/**'
      - 'app1/**'
      - '.github/workflows/**'
    branches:
      - "main"

permissions:
  id-token: write
  contents: read

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      infra: ${{ steps.filter.outputs.infra }}
      app1: ${{ steps.filter.outputs.app1 }}
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          infra:
            - 'infrastructure/**'
          app1:
            - 'app1/**'

  call-infra:
    needs: changes
    if: ${{ needs.changes.outputs.infra == 'true' }}
    uses: ./.github/workflows/workflow-infra.yml
    secrets: inherit

  call-app:
    if: always() && needs.call-infra != 'failure'
    needs: call-infra
    uses: ./.github/workflows/workflow-app.yml
    secrets: inherit
    with:
      app1: ${{ needs.changes.outputs.app1 }}
