name: Environments test

on:
  push:
    branches:
      - "main"

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: deploy
        run: echo 'environments test'
