name: Main workflow

on:
  push:
    paths:
      - 'infrastructure/**'
      - 'app1/**'
      - '.github/workflows/**'
    branches:
      - "main"

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      infra: ${{ steps.filter.outputs.infra }}
      app1: ${{ steps.filter.outputs.app1 }}
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          infra:
            - 'infrastructure/**'
          app1:
            - 'app1/**'

  call-infra:
    needs: changes
    if: ${{ needs.changes.outputs.infra == 'true' }}
    uses: ./.github/workflows/workflow-infra.yml
    secrets: inherit

  call-app:
    needs: call-infra
    if: ${{ ! failure() }}
    uses: ./.github/workflows/workflow-app.yml
    secrets: inherit
