name: DB workflow

on:
  workflow_call:
    inputs:
      db1:
        type: string
        required: true
    secrets:
      SECRET_1:
        required: true

jobs:
  call-db1:
    uses: ./.github/workflows/workflow-db1.yml
    secrets: inherit

  # call-app1:
  #   uses: ./.github/workflows/workflow-app1.yml
  #   secrets: inherit
