name: App workflow

on:
  workflow_call:
    inputs:
      infra:
        type: string
        required: true

jobs:
  call-infra:
    if: ${{ inputs.infra == 'true' }}
    uses: ./.github/workflows/workflow-infra.yml
    secrets: inherit

  call-test:
    runs-on: ubuntu-latest
    needs: call-infra
    steps:
    - name: Run Shell
      run: echo "Hello World"
