name: App workflow

on:
  workflow_call:
    inputs:
      is_app1_changed:
        required: true
    secrets:
      SECRET_1:
        required: true

jobs:
  call-app1:
    if: ${{ is-app1-changed == 'true' }}
    uses: ./.github/workflows/workflow-app1.yml
    secrets: inherit
