name: App workflow

on:
  workflow_call:
    inputs:
      app1:
        type: string
        required: true
    secrets:
      SECRET_1:
        required: true

jobs:
  call-app1:
    if: ${{ inputs.is_app1_changed == 'true' }}
    uses: ./.github/workflows/workflow-app1.yml
    secrets: inherit
