name: DB workflow

on:
  workflow_call:
    inputs:
      db1:
        type: string
        required: true

jobs:
  call-db1:
    # if: ${{ github.event.inputs.db1 == 'true' }}
    uses: a2-ito/github-environments-test/.github/workflows/workflow-db1.yml@main
    secrets: inherit

  # call-app1:
  #   uses: ./.github/workflows/workflow-app1.yml
  #   secrets: inherit
