name:App workflow

on:
  workflow_call:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo 'deploy app'

      - name: secrets
        run: echo ${{ secrets.SECRET_1 }}
