name: Main workflow

on:
  push:
    paths:
      - 'infrastructure/**'
      - 'app1/**'
      - '.github/workflows/**'
      - 'db1/**'
    branches:
      - "main"

permissions:
  id-token: write
  contents: read

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      infra: ${{ steps.filter.outputs.infra }}
      app1: ${{ steps.filter.outputs.app1 }}
      db1: ${{ steps.filter.outputs.db1 }}
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          infra:
            - 'infrastructure/**'
          app1:
            - 'app1/**'
          db1:
            - 'db1/**'

  call-infra:
    needs: changes
    uses: ./.github/workflows/workflow-call-infra.yml
    secrets: inherit
    with:
      infra: ${{ needs.changes.outputs.infra }}

  # call-infra:
  #   needs: changes
  #   uses: ./.github/workflows/workflow-infra.yml
  #   secrets: inherit

  call-db-test:
    runs-on: ubuntu-latest
    needs: call-infra
    if: always() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled')
    steps:
    - name: Run Shell
      run: echo "Hello World"

  # needs で指定したジョブがスキップした場合、changes の outputs が 正しく取得できなくてスキップされてしまう
  # call-infra がスキップされた場合のジョブと、スキップされていない場合のジョブを用意しておく

  # スキップされていない場合
  call-db1:
    #if: ${{ ! failure() }}
    needs: call-infra
    if: always() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') && ${{ needs.changes.outputs.db1 }}
      # if: always() && ${{ needs.changes.outputs.db1 }}
      # if: always() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled')
    uses: ./.github/workflows/workflow-db.yml
    secrets: inherit
    with:
      db1: ${{ needs.changes.outputs.db1 }}

  # スキップされた場合
  # call-db1 と重複して処理されないようにする必要がある
  call-db1-skipped:
    needs: changes
    if: needs.call-infra.result == 'skipped`'
    uses: ./.github/workflows/workflow-db.yml
    secrets: inherit
    with:
      db1: ${{ needs.changes.outputs.db1 }}

  call-app1:
    if: always()
    needs: call-infra
    uses: ./.github/workflows/workflow-app.yml
    secrets: inherit
    with:
      app1: ${{ needs.changes.outputs.app1 }}
